### ISSUE TITLE
About Large-scale Dataset Release

### ISSUE THREAD

**Issue by wbstx** [jonbarron/camp_zipnerf#18]
Congrats on the impressive works! I believe that they will inspire numerous future works.
Also, sorry for the unrelated question, but I would like to know whether there are any plans to release the large-scale dataset showed in the Zip-NeRF teaser video and described in SMERF (berlin, nyc, alameda, london)?
Thanks!

**Comment by jonbarron** [comment]
Yes, should happen soon.

**Comment by wbstx** [comment]
Thank you, I look forward to it!
