### ISSUE TITLE
Multi-Resolution Hash Grid Implementation

### ISSUE THREAD

**Issue by fhahlbohm** [jonbarron/camp_zipnerf#3]
Hey,

I have been looking forward to this code release for the past few months and now it is finally here! Thank you for your awesome work. The code looks really clean and I think it is great that you uploaded test set renderings for comparisons!

I have a few questions regarding the hash grid implementation.

1. Where exactly can I find the `triton_grids_inferface` that is used within `grid_utils.py`? I might be missing something very simple here, sorry.
2. I assume I could easily figure this out myself with the answer to 1., but what exactly is the idea behind the `precondition_scaling`?
3. Did you somehow evaluate your hash grid implementation compared to the one from tiny-cuda-nn wrt. reconstruction quality and speed?

Looking forward to your answer!

**Comment by jonbarron** [comment]
1) Oops, those triton stubs shouldn't be there, I've deleted them
2) That parameter rescales the grid parameters under the hood, which has a preconditioning effect. It's basically a hacky way to change Adam's learning rate for a subset of parameters.
3) Nope! I'm guessing ours is slower, it's just straight JAX with no CUDA or optimization.
