### ISSUE TITLE
Resume possible?

### ISSUE THREAD

**Issue by Iliceth** [jonbarron/camp_zipnerf#5]
I have run a test with the gardenvase dataset, did train, evaluate and then rendered the 480 frames, to then end abruptly, as it expected ffmpeg to be installed, which was not in the requirements. `RuntimeError: Program 'ffmpeg' is not found`

Rather not go through the +-90 minutes to render the frames again, I wondered if I can resume in some way from that point. Any advice? I now have a render-folder with 1920 files (4.3 GB) of generated data, for acc_, color_, distance_mean_ and distance_median_.

**Comment by ichsan2895** [comment]
Well, that is happen to me too. Rendering for +-60 minutes and forget to install ffmpeg

**Comment by jonbarron** [comment]
Thanks for flagging this, I've added ffmpeg as a requirement.

As for your first question, I don't see an easy solution besides just hacking the render script to skip a few indices.
